name: Build and Deploy

on:
  push:
    branches: [ main ]  # main 브랜치에 push 시 동작

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        env:
            DOCKER_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -f app/Dockerfile -t my-docker-image:${{ github.sha }} .
      
      - name: Push Docker Image
        run: |
          docker push my-docker-image:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}       # 예: 3.34.178.2
          username: ${{ secrets.EC2_USER }}     # 예: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}       # PEM 파일 내용
          script: |
            docker pull my-docker-image:${{ github.sha }}
            docker stop my-container || true
            docker rm my-container || true
            docker run -d --name my-container -p 80:80 my-docker-image:${{ github.sha }}
