name: Test Secrets

on:
  push:
    branches:
      - backend
  workflow_dispatch:  # 수동 실행 가능하도록 설정

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Required Secrets
        run: |
          check_secret() {
            if [[ -z "$1" ]]; then
              echo "❌ $2 is NOT set!"
              exit 1
            else
              echo "✅ $2 is set!"
            fi
          }

          check_secret "${{ secrets.DOCKER_USERNAME }}" "DOCKER_USERNAME"
          check_secret "${{ secrets.DOCKER_PASSWORD }}" "DOCKER_PASSWORD"
          check_secret "${{ secrets.EC2_HOST }}" "EC2_HOST"
          check_secret "${{ secrets.EC2_USER }}" "EC2_USER"
          check_secret "${{ secrets.EC2_SSH_KEY }}" "EC2_SSH_KEY"
          check_secret "${{ secrets.MONGODB_URI }}" "MONGODB_URI"
